version: "3.8"
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    # command: --default-authentication-plugin=mysql_native_password # localでDBクライアントなどで接続したい場合はコメントアウトを外す
    volumes:
      - db-store:/var/lib/mysql
#      - ./containers/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=runpush_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"
  web:
    build:
      context: .
      dockerfile: containers/app/nginx/Dockerfile
    ports:
      - "8001:80"
    depends_on:
      - app
    volumes:
      - ../app/:/var/www/html/app
  app:
    build:
      context: .
      dockerfile: containers/app/php/Dockerfile
    depends_on:
      - db
    volumes:
      - ../app/:/var/www/html/app

# 追記
volumes:
  db-store:
